name: Test React and Flask Applications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-webapp:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Install React dependencies
      run: |
        cd movie-frontend
        npm install
        cd ..

    # Step 4: Run Makefile webapp command
    - name: Start web application
      run: |
        make webapp &
        sleep 10 # Give time for the apps to start

    # Step 5: Verify Flask is running
    - name: Verify Flask is running
      run: |
        curl -f http://localhost:5001 || exit 1

    # Step 6: Verify React is running
    - name: Verify React is running
      run: |
        curl -f http://localhost:3000 || exit 1

    # Step 7: Clean up
    - name: Stop background processes
      run: |
        pkill -f flask || true
        pkill -f npm || true